# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: ARTIFACT2 CI GitHub workflow

on: 
  push:
   branches: [  "feature-*" ]
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
       ls -la
       pwd
       cat release.txt
       module=$(cat release.txt | grep -i comp_name | cut -d ":" -f2)
       echo $module
       echo "artifact=$(echo $module)"  >> "$GITHUB_ENV"
       mvn clean compile --file artifact2/pom.xml 

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Run Tests with Maven
      run: mvn -B test --file artifact2/pom.xml 

  deploytodev:
    name: 'Deploytodev'
    runs-on: ubuntu-latest
    steps:
    - name: Run deployment scripts
      run: echo 'Deployment step in progress...'
